export default {
  url: 'https://gitlab.com/api/v4/projects/70348379/repository/files/',
  languages: ['en', 'fr', 'es', 'pt', 'de', 'br', 'eo', 'ro', 'zh', 'ar', 'el', 'ko', 'ru', 'fi', 'vi'],
  books: [
    { "id": "gn", "pt": "Gênesis", "en": "Genesis", "fr": "", "es": "" },
    { "id": "ex", "pt": "Êxodo", "en": "Exodus", "fr": "", "es": "" },
    { "id": "lv", "pt": "Levítico", "en": "Leviticus", "fr": "", "es": "" },
    { "id": "nm", "pt": "Números", "en": "Numbers", "fr": "", "es": "" },
    { "id": "dt", "pt": "Deuteronômio", "en": "Deuteronomy", "fr": "", "es": "" },
    { "id": "js", "pt": "Josué", "en": "Joshua", "fr": "", "es": "" },
    { "id": "jud", "pt": "Juízes", "en": "Judges", "fr": "", "es": "" },
    { "id": "rt", "pt": "Rute", "en": "Ruth", "fr": "", "es": "" },
    { "id": "1sm", "pt": "1 Samuel", "en": "1 Samuel", "fr": "", "es": "" },
    { "id": "2sm", "pt": "2 Samuel", "en": "2 Samuel", "fr": "", "es": "" },
    { "id": "1kgs", "pt": "1 Reis", "en": "1 Kings", "fr": "", "es": "" },
    { "id": "2kgs", "pt": "2 Reis", "en": "3 Kings", "fr": "", "es": "" },
    { "id": "1ch", "pt": "1 Crônicas", "en": "1 Chronicles", "fr": "", "es": "" },
    { "id": "2ch", "pt": "2 Crônicas", "en": "2 Chronicles", "fr": "", "es": "" },
    { "id": "ez", "pt": "Esdras", "en": "Ezra", "fr": "", "es": "" },
    { "id": "ne", "pt": "Neemias", "en": "Nehemiah", "fr": "", "es": "" },
    { "id": "et", "pt": "Ester", "en": "Esther", "fr": "", "es": "" },
    { "id": "job", "pt": "Jó", "en": "Job", "fr": "", "es": "" },
    { "id": "ps", "pt": "Salmos", "en": "Psalm", "fr": "", "es": "" },
    { "id": "pr", "pt": "Provérbios", "en": "Proverbs", "fr": "", "es": "" },
    { "id": "ec", "pt": "Eclesiastes", "en": "Ecclesiastes", "fr": "", "es": "" },
    { "id": "so", "pt": "Cânticos", "en": "Songs of Solomon", "fr": "", "es": "" },
    { "id": "is", "pt": "Isaías", "en": "Isaiah", "fr": "", "es": "" },
    { "id": "jr", "pt": "Jeremias", "en": "Jeremiah", "fr": "", "es": "" },
    { "id": "lm", "pt": "Lamentações de Jeremias", "en": "Lamentations", "fr": "", "es": "" },
    { "id": "ez", "pt": "Ezequiel", "en": "Ezekiel", "fr": "", "es": "" },
    { "id": "dn", "pt": "Daniel", "en": "Daniel", "fr": "", "es": "" },
    { "id": "ho", "pt": "Oséias", "en": "Hosea", "fr": "", "es": "" },
    { "id": "jl", "pt": "Joel", "en": "Joel", "fr": "", "es": "" },
    { "id": "am", "pt": "Amós", "en": "Amos", "fr": "", "es": "" },
    { "id": "ob", "pt": "Obadias", "en": "Obadiah", "fr": "", "es": "" },
    { "id": "jn", "pt": "Jonas", "en": "Jonah", "fr": "", "es": "" },
    { "id": "mi", "pt": "Miquéias", "en": "Micah", "fr": "", "es": "" },
    { "id": "na", "pt": "Naum", "en": "Nahum", "fr": "", "es": "" },
    { "id": "hk", "pt": "Habacuque", "en": "Habakkuk", "fr": "", "es": "" },
    { "id": "zp", "pt": "Sofonias", "en": "Zephaniah", "fr": "", "es": "" },
    { "id": "hg", "pt": "Ageu", "en": "Haggai", "fr": "", "es": "" },
    { "id": "zc", "pt": "Zacarias", "Zechariah": "", "fr": "", "es": "" },
    { "id": "ml", "pt": "Malaquias", "en": "Malachi", "fr": "", "es": "" },
    { "id": "mt", "pt": "Mateus", "en": "Matthew", "fr": "", "es": "" },
    { "id": "mk", "pt": "Marcos", "en": "Mark", "fr": "", "es": "" },
    { "id": "lk", "pt": "Lucas", "en": "Luke", "fr": "", "es": "" },
    { "id": "jo", "pt": "João", "en": "John", "fr": "", "es": "" },
    { "id": "act", "pt": "Atos", "en": "Acts", "fr": "", "es": "" },
    { "id": "rm", "pt": "Romanos", "en": "Romans", "fr": "", "es": "" },
    { "id": "1co", "pt": "1 Coríntios", "en": "1 Corinthians", "fr": "", "es": "" },
    { "id": "2co", "pt": "2 Coríntios", "en": "2 Corinthians", "fr": "", "es": "" },
    { "id": "gl", "pt": "Gálatas", "en": "Galatians", "fr": "", "es": "" },
    { "id": "eph", "pt": "Efésios", "en": "Ephesians", "fr": "", "es": "" },
    { "id": "ph", "pt": "Filipenses", "en": "Philippians", "fr": "", "es": "" },
    { "id": "cl", "pt": "Colossenses", "en": "Colossians", "fr": "", "es": "" },
    { "id": "1ts", "pt": "1 Tessalonicenses", "en": "1 Thessalonians", "fr": "", "es": "" },
    { "id": "2ts", "pt": "2 Tessalonicenses", "en": "2 Thessalonians", "fr": "", "es": "" },
    { "id": "1tm", "pt": "1 Timóteo", "en": "1 Timothy", "fr": "", "es": "" },
    { "id": "2tm", "pt": "2 Timóteo", "en": "2 Timothy", "fr": "", "es": "" },
    { "id": "tt", "pt": "Tito", "en": "Titus", "fr": "", "es": "" },
    { "id": "phm", "pt": "Filemom", "en": "Philemon", "fr": "", "es": "" },
    { "id": "hb", "pt": "Hebreus", "en": "Hebrews", "fr": "", "es": "" },
    { "id": "jm", "pt": "Tiago", "en": "James", "fr": "", "es": "" },
    { "id": "1pe", "pt": "1 Pedro", "en": "1 Peter", "fr": "", "es": "" },
    { "id": "2pe", "pt": "2 Pedro", "en": "2 Peter", "fr": "", "es": "" },
    { "id": "1jo", "pt": "1 João", "en": "1 John", "fr": "", "es": "" },
    { "id": "2jo", "pt": "2 João", "en": "2 John", "fr": "", "es": "" },
    { "id": "3jo", "pt": "3 João", "en": "3 John", "fr": "", "es": "" },
    { "id": "jd", "pt": "Judas", "en": "Jude", "fr": "", "es": "" },
    { "id": "re", "pt": "Apocalipse", "en": "Revelation", "fr": "", "es": "" }
  ]
}
